language: rust
sudo: false
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

# run builds for both all the trains
rust:
  - nightly
  - beta
  - stable

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
after_success:
  # upload the documentation from the build with beta (automatically only actually
  # runs on the master branch)
  - travis-cargo --only stable doc
  - travis-cargo --only stable doc-upload
  # measure code coverage and upload to coveralls.io
  - travis-cargo coveralls --no-sudo

env:
  global:
    - secure: "Azb2kN3sVX4KYy4LCrqUqmvCOoePRfDcq9EVfPuJxexrKbkubU4WRxay13ZwGKLvdiL6MXeGYdaNdULDDoxFdREid6T8ZwXdVgEYRg6RanBXs4PME8PNAk3sr0vX92jUpPe6uiLTi3HFilD96IXM/QuPgmjaTUGlxg/tNqVvMO1MnVhSZw8nbC3GRX8K/iMzBE1J0bbYc0nQ5KR2QDLuUPl7ddYzA/OeXxkOdGc3oPAXL3JveRvKRN6WfCbtzn31AYPba2h3LQ6r4XzwL4ZGU1Kpvm/CWsNGtRhZHJ5fh5TFZzVKlK8ndEM747ApdiyYkbpSUCFqkU6W8MP2fwSBH9HK4n6MKY/JZUFc6D0HhDpfgOcRrvRgydkHR5ubQx/+PRfvh3jxDaMGizlxiKGlKaFctxkB2JZCGFm+kGnKNRhxj7ibsDVDn2Mx72x0wE5LAybqsx3eoBno/DPU04YeGCVuA9BIzLQunCa051sxH1/UPUe2tE0cios2SUVLKtCDgawLohWwWDrBQU4hk6ZepZlYY2jo/vRq+xYkYH1ISUDNacu6lu8vfkFBOZBfDmIQQK0+fHnZI7TLeLfbW0iR7Ep9dgbAkw829OpMUof9Kk1YPfIlJ4CUkFKtKH2vP15+QRyDt6oDzSHlmpJLNQECoTG7gMsxsRRBrr5gI5eYtqI="
    - RUST_TEST_THREADS=1
